/**
 * Autogenerated by Thrift Compiler (0.20.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package es.udc.ws.courses.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.20.0)", date = "2024-12-26")
public class ThriftInscriptionDto implements org.apache.thrift.TBase<ThriftInscriptionDto, ThriftInscriptionDto._Fields>, java.io.Serializable, Cloneable, Comparable<ThriftInscriptionDto> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ThriftInscriptionDto");

  private static final org.apache.thrift.protocol.TField INSCRIPTION_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("inscriptionId", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField COURSE_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("courseId", org.apache.thrift.protocol.TType.I64, (short)2);
  private static final org.apache.thrift.protocol.TField USER_EMAIL_FIELD_DESC = new org.apache.thrift.protocol.TField("userEmail", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField CREDIT_CARD_NUMBER_FIELD_DESC = new org.apache.thrift.protocol.TField("creditCardNumber", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField INSCRIPTION_DATE_FIELD_DESC = new org.apache.thrift.protocol.TField("inscriptionDate", org.apache.thrift.protocol.TType.STRING, (short)5);
  private static final org.apache.thrift.protocol.TField CANCEL_DATE_FIELD_DESC = new org.apache.thrift.protocol.TField("cancelDate", org.apache.thrift.protocol.TType.STRING, (short)6);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ThriftInscriptionDtoStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ThriftInscriptionDtoTupleSchemeFactory();

  public long inscriptionId; // required
  public long courseId; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String userEmail; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String creditCardNumber; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String inscriptionDate; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String cancelDate; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    INSCRIPTION_ID((short)1, "inscriptionId"),
    COURSE_ID((short)2, "courseId"),
    USER_EMAIL((short)3, "userEmail"),
    CREDIT_CARD_NUMBER((short)4, "creditCardNumber"),
    INSCRIPTION_DATE((short)5, "inscriptionDate"),
    CANCEL_DATE((short)6, "cancelDate");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // INSCRIPTION_ID
          return INSCRIPTION_ID;
        case 2: // COURSE_ID
          return COURSE_ID;
        case 3: // USER_EMAIL
          return USER_EMAIL;
        case 4: // CREDIT_CARD_NUMBER
          return CREDIT_CARD_NUMBER;
        case 5: // INSCRIPTION_DATE
          return INSCRIPTION_DATE;
        case 6: // CANCEL_DATE
          return CANCEL_DATE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __INSCRIPTIONID_ISSET_ID = 0;
  private static final int __COURSEID_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.INSCRIPTION_ID, new org.apache.thrift.meta_data.FieldMetaData("inscriptionId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.COURSE_ID, new org.apache.thrift.meta_data.FieldMetaData("courseId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.USER_EMAIL, new org.apache.thrift.meta_data.FieldMetaData("userEmail", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CREDIT_CARD_NUMBER, new org.apache.thrift.meta_data.FieldMetaData("creditCardNumber", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.INSCRIPTION_DATE, new org.apache.thrift.meta_data.FieldMetaData("inscriptionDate", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CANCEL_DATE, new org.apache.thrift.meta_data.FieldMetaData("cancelDate", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ThriftInscriptionDto.class, metaDataMap);
  }

  public ThriftInscriptionDto() {
  }

  public ThriftInscriptionDto(
    long inscriptionId,
    long courseId,
    java.lang.String userEmail,
    java.lang.String creditCardNumber,
    java.lang.String inscriptionDate,
    java.lang.String cancelDate)
  {
    this();
    this.inscriptionId = inscriptionId;
    setInscriptionIdIsSet(true);
    this.courseId = courseId;
    setCourseIdIsSet(true);
    this.userEmail = userEmail;
    this.creditCardNumber = creditCardNumber;
    this.inscriptionDate = inscriptionDate;
    this.cancelDate = cancelDate;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ThriftInscriptionDto(ThriftInscriptionDto other) {
    __isset_bitfield = other.__isset_bitfield;
    this.inscriptionId = other.inscriptionId;
    this.courseId = other.courseId;
    if (other.isSetUserEmail()) {
      this.userEmail = other.userEmail;
    }
    if (other.isSetCreditCardNumber()) {
      this.creditCardNumber = other.creditCardNumber;
    }
    if (other.isSetInscriptionDate()) {
      this.inscriptionDate = other.inscriptionDate;
    }
    if (other.isSetCancelDate()) {
      this.cancelDate = other.cancelDate;
    }
  }

  @Override
  public ThriftInscriptionDto deepCopy() {
    return new ThriftInscriptionDto(this);
  }

  @Override
  public void clear() {
    setInscriptionIdIsSet(false);
    this.inscriptionId = 0;
    setCourseIdIsSet(false);
    this.courseId = 0;
    this.userEmail = null;
    this.creditCardNumber = null;
    this.inscriptionDate = null;
    this.cancelDate = null;
  }

  public long getInscriptionId() {
    return this.inscriptionId;
  }

  public ThriftInscriptionDto setInscriptionId(long inscriptionId) {
    this.inscriptionId = inscriptionId;
    setInscriptionIdIsSet(true);
    return this;
  }

  public void unsetInscriptionId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __INSCRIPTIONID_ISSET_ID);
  }

  /** Returns true if field inscriptionId is set (has been assigned a value) and false otherwise */
  public boolean isSetInscriptionId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __INSCRIPTIONID_ISSET_ID);
  }

  public void setInscriptionIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __INSCRIPTIONID_ISSET_ID, value);
  }

  public long getCourseId() {
    return this.courseId;
  }

  public ThriftInscriptionDto setCourseId(long courseId) {
    this.courseId = courseId;
    setCourseIdIsSet(true);
    return this;
  }

  public void unsetCourseId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __COURSEID_ISSET_ID);
  }

  /** Returns true if field courseId is set (has been assigned a value) and false otherwise */
  public boolean isSetCourseId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __COURSEID_ISSET_ID);
  }

  public void setCourseIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __COURSEID_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getUserEmail() {
    return this.userEmail;
  }

  public ThriftInscriptionDto setUserEmail(@org.apache.thrift.annotation.Nullable java.lang.String userEmail) {
    this.userEmail = userEmail;
    return this;
  }

  public void unsetUserEmail() {
    this.userEmail = null;
  }

  /** Returns true if field userEmail is set (has been assigned a value) and false otherwise */
  public boolean isSetUserEmail() {
    return this.userEmail != null;
  }

  public void setUserEmailIsSet(boolean value) {
    if (!value) {
      this.userEmail = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getCreditCardNumber() {
    return this.creditCardNumber;
  }

  public ThriftInscriptionDto setCreditCardNumber(@org.apache.thrift.annotation.Nullable java.lang.String creditCardNumber) {
    this.creditCardNumber = creditCardNumber;
    return this;
  }

  public void unsetCreditCardNumber() {
    this.creditCardNumber = null;
  }

  /** Returns true if field creditCardNumber is set (has been assigned a value) and false otherwise */
  public boolean isSetCreditCardNumber() {
    return this.creditCardNumber != null;
  }

  public void setCreditCardNumberIsSet(boolean value) {
    if (!value) {
      this.creditCardNumber = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getInscriptionDate() {
    return this.inscriptionDate;
  }

  public ThriftInscriptionDto setInscriptionDate(@org.apache.thrift.annotation.Nullable java.lang.String inscriptionDate) {
    this.inscriptionDate = inscriptionDate;
    return this;
  }

  public void unsetInscriptionDate() {
    this.inscriptionDate = null;
  }

  /** Returns true if field inscriptionDate is set (has been assigned a value) and false otherwise */
  public boolean isSetInscriptionDate() {
    return this.inscriptionDate != null;
  }

  public void setInscriptionDateIsSet(boolean value) {
    if (!value) {
      this.inscriptionDate = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getCancelDate() {
    return this.cancelDate;
  }

  public ThriftInscriptionDto setCancelDate(@org.apache.thrift.annotation.Nullable java.lang.String cancelDate) {
    this.cancelDate = cancelDate;
    return this;
  }

  public void unsetCancelDate() {
    this.cancelDate = null;
  }

  /** Returns true if field cancelDate is set (has been assigned a value) and false otherwise */
  public boolean isSetCancelDate() {
    return this.cancelDate != null;
  }

  public void setCancelDateIsSet(boolean value) {
    if (!value) {
      this.cancelDate = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case INSCRIPTION_ID:
      if (value == null) {
        unsetInscriptionId();
      } else {
        setInscriptionId((java.lang.Long)value);
      }
      break;

    case COURSE_ID:
      if (value == null) {
        unsetCourseId();
      } else {
        setCourseId((java.lang.Long)value);
      }
      break;

    case USER_EMAIL:
      if (value == null) {
        unsetUserEmail();
      } else {
        setUserEmail((java.lang.String)value);
      }
      break;

    case CREDIT_CARD_NUMBER:
      if (value == null) {
        unsetCreditCardNumber();
      } else {
        setCreditCardNumber((java.lang.String)value);
      }
      break;

    case INSCRIPTION_DATE:
      if (value == null) {
        unsetInscriptionDate();
      } else {
        setInscriptionDate((java.lang.String)value);
      }
      break;

    case CANCEL_DATE:
      if (value == null) {
        unsetCancelDate();
      } else {
        setCancelDate((java.lang.String)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case INSCRIPTION_ID:
      return getInscriptionId();

    case COURSE_ID:
      return getCourseId();

    case USER_EMAIL:
      return getUserEmail();

    case CREDIT_CARD_NUMBER:
      return getCreditCardNumber();

    case INSCRIPTION_DATE:
      return getInscriptionDate();

    case CANCEL_DATE:
      return getCancelDate();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case INSCRIPTION_ID:
      return isSetInscriptionId();
    case COURSE_ID:
      return isSetCourseId();
    case USER_EMAIL:
      return isSetUserEmail();
    case CREDIT_CARD_NUMBER:
      return isSetCreditCardNumber();
    case INSCRIPTION_DATE:
      return isSetInscriptionDate();
    case CANCEL_DATE:
      return isSetCancelDate();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof ThriftInscriptionDto)
      return this.equals((ThriftInscriptionDto)that);
    return false;
  }

  public boolean equals(ThriftInscriptionDto that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_inscriptionId = true;
    boolean that_present_inscriptionId = true;
    if (this_present_inscriptionId || that_present_inscriptionId) {
      if (!(this_present_inscriptionId && that_present_inscriptionId))
        return false;
      if (this.inscriptionId != that.inscriptionId)
        return false;
    }

    boolean this_present_courseId = true;
    boolean that_present_courseId = true;
    if (this_present_courseId || that_present_courseId) {
      if (!(this_present_courseId && that_present_courseId))
        return false;
      if (this.courseId != that.courseId)
        return false;
    }

    boolean this_present_userEmail = true && this.isSetUserEmail();
    boolean that_present_userEmail = true && that.isSetUserEmail();
    if (this_present_userEmail || that_present_userEmail) {
      if (!(this_present_userEmail && that_present_userEmail))
        return false;
      if (!this.userEmail.equals(that.userEmail))
        return false;
    }

    boolean this_present_creditCardNumber = true && this.isSetCreditCardNumber();
    boolean that_present_creditCardNumber = true && that.isSetCreditCardNumber();
    if (this_present_creditCardNumber || that_present_creditCardNumber) {
      if (!(this_present_creditCardNumber && that_present_creditCardNumber))
        return false;
      if (!this.creditCardNumber.equals(that.creditCardNumber))
        return false;
    }

    boolean this_present_inscriptionDate = true && this.isSetInscriptionDate();
    boolean that_present_inscriptionDate = true && that.isSetInscriptionDate();
    if (this_present_inscriptionDate || that_present_inscriptionDate) {
      if (!(this_present_inscriptionDate && that_present_inscriptionDate))
        return false;
      if (!this.inscriptionDate.equals(that.inscriptionDate))
        return false;
    }

    boolean this_present_cancelDate = true && this.isSetCancelDate();
    boolean that_present_cancelDate = true && that.isSetCancelDate();
    if (this_present_cancelDate || that_present_cancelDate) {
      if (!(this_present_cancelDate && that_present_cancelDate))
        return false;
      if (!this.cancelDate.equals(that.cancelDate))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(inscriptionId);

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(courseId);

    hashCode = hashCode * 8191 + ((isSetUserEmail()) ? 131071 : 524287);
    if (isSetUserEmail())
      hashCode = hashCode * 8191 + userEmail.hashCode();

    hashCode = hashCode * 8191 + ((isSetCreditCardNumber()) ? 131071 : 524287);
    if (isSetCreditCardNumber())
      hashCode = hashCode * 8191 + creditCardNumber.hashCode();

    hashCode = hashCode * 8191 + ((isSetInscriptionDate()) ? 131071 : 524287);
    if (isSetInscriptionDate())
      hashCode = hashCode * 8191 + inscriptionDate.hashCode();

    hashCode = hashCode * 8191 + ((isSetCancelDate()) ? 131071 : 524287);
    if (isSetCancelDate())
      hashCode = hashCode * 8191 + cancelDate.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(ThriftInscriptionDto other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetInscriptionId(), other.isSetInscriptionId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetInscriptionId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.inscriptionId, other.inscriptionId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetCourseId(), other.isSetCourseId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCourseId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.courseId, other.courseId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetUserEmail(), other.isSetUserEmail());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUserEmail()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.userEmail, other.userEmail);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetCreditCardNumber(), other.isSetCreditCardNumber());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCreditCardNumber()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.creditCardNumber, other.creditCardNumber);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetInscriptionDate(), other.isSetInscriptionDate());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetInscriptionDate()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.inscriptionDate, other.inscriptionDate);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetCancelDate(), other.isSetCancelDate());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCancelDate()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.cancelDate, other.cancelDate);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("ThriftInscriptionDto(");
    boolean first = true;

    sb.append("inscriptionId:");
    sb.append(this.inscriptionId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("courseId:");
    sb.append(this.courseId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("userEmail:");
    if (this.userEmail == null) {
      sb.append("null");
    } else {
      sb.append(this.userEmail);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("creditCardNumber:");
    if (this.creditCardNumber == null) {
      sb.append("null");
    } else {
      sb.append(this.creditCardNumber);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("inscriptionDate:");
    if (this.inscriptionDate == null) {
      sb.append("null");
    } else {
      sb.append(this.inscriptionDate);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("cancelDate:");
    if (this.cancelDate == null) {
      sb.append("null");
    } else {
      sb.append(this.cancelDate);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ThriftInscriptionDtoStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public ThriftInscriptionDtoStandardScheme getScheme() {
      return new ThriftInscriptionDtoStandardScheme();
    }
  }

  private static class ThriftInscriptionDtoStandardScheme extends org.apache.thrift.scheme.StandardScheme<ThriftInscriptionDto> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, ThriftInscriptionDto struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // INSCRIPTION_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.inscriptionId = iprot.readI64();
              struct.setInscriptionIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // COURSE_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.courseId = iprot.readI64();
              struct.setCourseIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // USER_EMAIL
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.userEmail = iprot.readString();
              struct.setUserEmailIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // CREDIT_CARD_NUMBER
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.creditCardNumber = iprot.readString();
              struct.setCreditCardNumberIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // INSCRIPTION_DATE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.inscriptionDate = iprot.readString();
              struct.setInscriptionDateIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // CANCEL_DATE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.cancelDate = iprot.readString();
              struct.setCancelDateIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, ThriftInscriptionDto struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(INSCRIPTION_ID_FIELD_DESC);
      oprot.writeI64(struct.inscriptionId);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(COURSE_ID_FIELD_DESC);
      oprot.writeI64(struct.courseId);
      oprot.writeFieldEnd();
      if (struct.userEmail != null) {
        oprot.writeFieldBegin(USER_EMAIL_FIELD_DESC);
        oprot.writeString(struct.userEmail);
        oprot.writeFieldEnd();
      }
      if (struct.creditCardNumber != null) {
        oprot.writeFieldBegin(CREDIT_CARD_NUMBER_FIELD_DESC);
        oprot.writeString(struct.creditCardNumber);
        oprot.writeFieldEnd();
      }
      if (struct.inscriptionDate != null) {
        oprot.writeFieldBegin(INSCRIPTION_DATE_FIELD_DESC);
        oprot.writeString(struct.inscriptionDate);
        oprot.writeFieldEnd();
      }
      if (struct.cancelDate != null) {
        oprot.writeFieldBegin(CANCEL_DATE_FIELD_DESC);
        oprot.writeString(struct.cancelDate);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ThriftInscriptionDtoTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public ThriftInscriptionDtoTupleScheme getScheme() {
      return new ThriftInscriptionDtoTupleScheme();
    }
  }

  private static class ThriftInscriptionDtoTupleScheme extends org.apache.thrift.scheme.TupleScheme<ThriftInscriptionDto> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ThriftInscriptionDto struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetInscriptionId()) {
        optionals.set(0);
      }
      if (struct.isSetCourseId()) {
        optionals.set(1);
      }
      if (struct.isSetUserEmail()) {
        optionals.set(2);
      }
      if (struct.isSetCreditCardNumber()) {
        optionals.set(3);
      }
      if (struct.isSetInscriptionDate()) {
        optionals.set(4);
      }
      if (struct.isSetCancelDate()) {
        optionals.set(5);
      }
      oprot.writeBitSet(optionals, 6);
      if (struct.isSetInscriptionId()) {
        oprot.writeI64(struct.inscriptionId);
      }
      if (struct.isSetCourseId()) {
        oprot.writeI64(struct.courseId);
      }
      if (struct.isSetUserEmail()) {
        oprot.writeString(struct.userEmail);
      }
      if (struct.isSetCreditCardNumber()) {
        oprot.writeString(struct.creditCardNumber);
      }
      if (struct.isSetInscriptionDate()) {
        oprot.writeString(struct.inscriptionDate);
      }
      if (struct.isSetCancelDate()) {
        oprot.writeString(struct.cancelDate);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ThriftInscriptionDto struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(6);
      if (incoming.get(0)) {
        struct.inscriptionId = iprot.readI64();
        struct.setInscriptionIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.courseId = iprot.readI64();
        struct.setCourseIdIsSet(true);
      }
      if (incoming.get(2)) {
        struct.userEmail = iprot.readString();
        struct.setUserEmailIsSet(true);
      }
      if (incoming.get(3)) {
        struct.creditCardNumber = iprot.readString();
        struct.setCreditCardNumberIsSet(true);
      }
      if (incoming.get(4)) {
        struct.inscriptionDate = iprot.readString();
        struct.setInscriptionDateIsSet(true);
      }
      if (incoming.get(5)) {
        struct.cancelDate = iprot.readString();
        struct.setCancelDateIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

